# config.yaml
version:
  name: PreventIdleApp
  version: "1.0.0"

scheduler:
  interval: "1s"      # 檢查閒置狀態的間隔時間

idlePrevention:
  enabled: true
  interval: "5s"      # 進入瑩幕保護前的閒置時間
  mode: "mouse"       # 模擬模式，可選：key, mouse, mixed

logging:
  level: "info"
  output: "console"   # 或指定檔案路徑

retryPolicy:
  maxRetries: 3
  retryInterval: "1s"

workSchedule:
  monday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  tuesday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  wednesday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  thursday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "17:00"
  friday:
    - start: "08:00"
      end: "12:00"
    - start: "13:00"
      end: "18:00"
  saturday: 
    - start: "08:00"
      end: "12:00"
    - start: "15:05"
      end: "18:00"
  sunday: []